### ISSUE TITLE
Update gopsutil package

### ISSUE THREAD

**Issue by geauxvirtual** [intelsdi-x/snap-plugin-collector-psutil#12]
We currently use gopsutil at a rev level of 1.0.0-64. While the project hasn't released a new release of the package since Dec 2014, there have been numerous commits to the project since 1.0.0-64, one of which change the directory structure of the project.

The issue is that with the recent issues we have been having with godep, if a user uses go get to download the plugin, go get will grab gopsutil at head. When make deps is run, godep tries to restore github.com/shirou/gopsutil/common, which currently does not exist in the project causing godep restore to fail.

The workaround is to use git to clone down the repo, then run make deps where godep restore will succeed.

**Comment by marcin-krolik** [comment]
@geauxvirtual as glide is managing dependencies now, issue is not longer valid. I added `glide.lock` which holds latest sha of `shirou/gopsutil`.

**Comment by nanliu** [comment]
This is resolved and can be closed.
