### ISSUE TITLE
unable to retrieve psutils metrics for Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz architecture

### ISSUE THREAD

**Issue by imvisiontech** [intelsdi-x/snap-plugin-collector-psutil#19]
Hi,
I tested the psutil plugin on Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz and it worked fine.
but I receive the following (see below) error when running on Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz. 
Is this architecture unsupported?

error received:
Metric not found: /intel/psutil/cpu0/user
Metric not found: /intel/psutil/cpu2/system
Metric not found: /intel/psutil/load/load1
Metric not found: /intel/psutil/load/load15
Metric not found: /intel/psutil/vm/cached
Metric not found: /intel/psutil/vm/wired
Metric not found: /intel/psutil/cpu1/system
Metric not found: /intel/psutil/cpu2/iowait
Metric not found: /intel/psutil/cpu2/irq
Metric not found: /intel/psutil/cpu2/stolen
Metric not found: /intel/psutil/load/load5
Metric not found: /intel/psutil/vm/available
Metric not found: /intel/psutil/cpu0/irq
Metric not found: /intel/psutil/cpu2/guest
Metric not found: /intel/psutil/vm/active
Metric not found: /intel/psutil/vm/buffers
Metric not found: /intel/psutil/vm/used_percent
Metric not found: /intel/psutil/cpu0/idle
Metric not found: /intel/psutil/cpu0/softirq
Metric not found: /intel/psutil/cpu0/system
Metric not found: /intel/psutil/cpu1/irq
Metric not found: /intel/psutil/cpu2/guest_nice
Metric not found: /intel/psutil/vm/free
Metric not found: /intel/psutil/cpu0/guest
Metric not found: /intel/psutil/cpu0/guest_nice
Metric not found: /intel/psutil/cpu0/steal
Metric not found: /intel/psutil/cpu1/nice
Metric not found: /intel/psutil/cpu1/steal
Metric not found: /intel/psutil/cpu2/user
Metric not found: /intel/psutil/cpu0/stolen
Metric not found: /intel/psutil/cpu1/softirq
Metric not found: /intel/psutil/cpu2/steal
Metric not found: /intel/psutil/vm/inactive
Metric not found: /intel/psutil/cpu0/nice
Metric not found: /intel/psutil/cpu1/guest
Metric not found: /intel/psutil/cpu1/idle
Metric not found: /intel/psutil/cpu1/stolen
Metric not found: /intel/psutil/cpu2/idle
Metric not found: /intel/psutil/vm/shared
Metric not found: /intel/psutil/vm/total
Metric not found: /intel/psutil/cpu0/iowait
Metric not found: /intel/psutil/cpu1/guest_nice
Metric not found: /intel/psutil/cpu1/iowait
Metric not found: /intel/psutil/cpu1/user
Metric not found: /intel/psutil/cpu2/nice
Metric not found: /intel/psutil/cpu2/softirq
Metric not found: /intel/psutil/vm/used

**Comment by IRCody** [comment]
@imvisiontech: I wouldn't think that the processor would be the problem. Can you give us more environment info, for example what operating system?

**Comment by IRCody** [comment]
@imvisiontech: I still don't think the processor would be the reason for this. Some troubleshooting things I think would be good to try:

* Is the plugin loaded? (`snapctl plugin list`)
* What metrics does snapd know about (`snapctl metric list`)

Info we would need to further help debug:
* snap version
* psutil version
* Where this error is being reported? (What action was taken that reported it)

**Comment by IRCody** [comment]
@imvisiontech: I'm going to close this issue since it's been open for awhile. If you'd like me to re-open please response with `@ircody` somewhere in the message and I will re-open.
