### ISSUE TITLE
missing some metrics for intel/psutil/vm/

### ISSUE THREAD

**Issue by msrba** [intelsdi-x/snap-plugin-collector-psutil#21]
I use snap-plugin-collector-psutil with snap version v0.13.0 for Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz. I missing the metric "intel/psutil/vm/shared". 

```
/opt/snap/bin/snapctl metric list | grep /intel/psutil/vm
/intel/psutil/vm/active                      6
/intel/psutil/vm/available                   6
/intel/psutil/vm/buffers                     6
/intel/psutil/vm/cached                      6
/intel/psutil/vm/free                        6
/intel/psutil/vm/inactive                    6
/intel/psutil/vm/total                       6
/intel/psutil/vm/used                        6
/intel/psutil/vm/used_percent                6
/intel/psutil/vm/wired                       6
```

**Comment by IRCody** [comment]
@msrba: Sorry for the delayed reply.

What OS are you using? the shared metric is Platform specific. For example I don't believe it's available on OSX.

**Comment by IRCody** [comment]
@msrba: I'm going to close this issue due to inactivity but if you come back and can provide more info please respond here with an `@ircody` and I will re-open.

**Comment by msrba** [comment]
We use snap on Ubuntu 14.04 and 16.04 both have the issue.

**Comment by IRCody** [comment]
Thanks for the info! I'll re-open. I can test on ubuntu 14.04 tomorrow.

**Comment by IzabellaRaulin** [comment]
I confirmed that the metric `/intel/psutil/vm/shared` is missing and what is more, it does not depend on system, just creating this metricType is missing - see [psutil/mem.go#L78](https://github.com/IzabellaRaulin/snap-plugin-collector-psutil/blob/master/psutil/mem.go#L78). I will take a look on that.

**Comment by IzabellaRaulin** [comment]
I found out that this field has been removed from **github.com/shirou/gopsutil/mem** in [commit 4438159, on Feb 17](https://github.com/shirou/gopsutil/commit/4438159155d9d2fbb0848e4374b8cb4bc59eb474). See in description:

> Document + add tests for for mem.VirtualMemory()
> This change changes and documents the (previously undocumented) behavior of Used
> to "RAM used by programs".
> 
> We also remove the undocumented and unused Shared field of that struct.

snap-plugin-collector-psutil uses that mem structure from github.com/shirou/gopsutil/mem and calls `mem.VirtualMemory()` and retrieves appropriate values from it, see [psutil/mem.go](https://github.com/intelsdi-x/snap-plugin-collector-psutil/blob/master/psutil/mem.go#L43).

**Comment by IRCody** [comment]
Thanks @IzabellaRaulin for tracking that down. It seems like the README.md should be updated to reflect these changes.
