### ISSUE TITLE
Metric Namespace Error while loading plugin snap-plugin-collector-psutil

### ISSUE THREAD

**Issue by amanRaina** [intelsdi-x/snap-plugin-collector-psutil#31]
I am getting the error while loading snap plugin snap-plugin-collector-psutil. The error is as below -
Error loading plugin:
Metric namespace /intel/psutil/net/ens513f1.226/errout contains not allowed characters. Avoid using  punctuations [. , ; ? !], slashes [| \ /], carets [^], quotations [" ` '], brackets [( ) [ ] { }], spaces [ ]

My tasks file looks like below-

---
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  max-failures: 10
  workflow:
    collect:
      metrics:
        /intel/psutil/*: {}
      config:
        /intel/mock:
          name: "root"
          password: "secret"
      publish:
        -
          plugin_name: "influx"
          config:
             host: "10.19.226.68"
             port: 8086
             database: "test"
             user: "root"
             password: "P@ssw0rd"

The OS details are as below -
CentOS Linux release 7.2.1511 (Core)
Kernel -
3.10.0-327.28.3.el7.x86_64

Let me know how to resolve this error?

**Comment by IRCody** [comment]
@amanRaina: This was an issue with Snap and not specific to this plugin. This behavior changed following [this](https://github.com/intelsdi-x/snap/pull/1220) PR. This will be part of the next release.

Could you try testing against a version of snapd built from master and let us verify that this resolves your issue?

**Comment by IRCody** [comment]
@amanRaina: Since the behavior around that particular error has changed and the issue has been open for awhile I'm going to close this. Please respond if it's still an issue with `@ircody` in the message and I can re-open.
