### ISSUE TITLE
Drop or fix darwin build for psutil

### ISSUE THREAD

**Issue by nanliu** [intelsdi-x/snap-plugin-collector-psutil#42]
psutil does not load on MacOS because [we only support cpu metrics on linux](https://github.com/intelsdi-x/snap-plugin-collector-psutil/blob/master/psutil/cpu.go#L199)

```
$ snapctl plugin load snap-plugin-collector-psutil
Error loading plugin:
GetMetricTypes call error : darwin not supported by plugin
```

Upstream gopsutil have resolved the [issue](https://github.com/shirou/gopsutil/issues/31), but requires cgo. At this point we need a decision whether we want to support this plugin for MacOS (which requires cgo and we can't easily generate universal binaries), or drop support and delete the darwin binary in the github release page.

cc @intelsdi-x/snap-maintainers

**Comment by mjbrender** [comment]
@nanliu psutil is our go-to example of using Snap, which makes me lean toward fixing it. I know our CI with cgo isn't the easiest. Do we have another plugin requiring cgo? 

FYI on this concern @jcooklin.

**Comment by marcin-krolik** [comment]
@mjbrender we don't have any other plugin which requires cgo

**Comment by sandlbn** [comment]
@marcin-krolik we have libvirt

**Comment by marcin-krolik** [comment]
@sandlbn thanks, was not aware about this one
